import { ROLES_ARRAY } from '~@/utils/constant'

export const menuData = [
  {
    id: 1,
    parentId: null,
    title: '仪表盘',
    icon: 'DashboardOutlined',
    component: 'RouteView',
    redirect: '/dashboard/analysis',
    path: '/dashboard',
    name: 'Dashboard',
    locale: 'menu.dashboard',
  },
  {
    id: 2,
    parentId: 1,
    title: '分析页',
    component: '/dashboard/analysis',
    path: '/dashboard/analysis',
    name: 'DashboardAnalysis',
    keepAlive: true,
    locale: 'menu.dashboard.analysis',
  },
  {
    id: 300,
    parentId: null,
    title: '订单管理',
    icon: 'CreditCardOutlined',
    component: 'RouteView',
    path: '/order',
    name: 'Order',
    locale: '订单管理',
  },
  {
    id: 301,
    parentId: 300,
    title: '订单列表',
    component: '/order/vendor/list',
    path: '/order/vendor/list',
    name: 'OrderVendorList',
    locale: '订单列表',
  },
  {
    id: 302,
    parentId: 300,
    title: '添加订单',
    component: '/order/vendor/form',
    path: '/order/vendor/form',
    name: 'OrderVendorForm',
    locale: '添加订单',
  },
  {
    id: 400,
    parentId: null,
    title: '财务管理',
    icon: 'PayCircleOutlined',
    component: 'RouteView',
    path: '/finance',
    name: 'Finance',
    locale: '财务管理',
  },
  {
    id: 401,
    parentId: 400,
    title: '财务流水',
    component: '/finance/vendor/waterfall',
    path: '/finance/vendor/waterfall',
    name: 'FinanceVendorWaterfall',
    locale: '财务流水',
  },
  {
    id: 402,
    parentId: 400,
    title: '财务统计',
    component: '/finance/vendor/statistics',
    path: '/finance/vendor/statistics',
    name: 'FinanceVendorStatistics',
    locale: '财务统计',
  },
  {
    id: 36,
    parentId: null,
    title: '个人页',
    icon: 'UserOutlined',
    component: 'RouteView',
    redirect: '/account/center',
    path: '/account',
    name: 'Account',
    locale: 'menu.account',
  },
  {
    id: 37,
    parentId: 36,
    path: '/account/center',
    title: '个人中心',
    name: 'AccountCenter',
    component: '/account/center',
    locale: 'menu.account.center',
  },
  {
    id: 38,
    parentId: 36,
    path: '/account/settings',
    title: '个人设置',
    name: 'AccountSettings',
    component: '/account/settings',
    locale: 'menu.account.settings',
  }
]

export const vendorAccessMenuData = [
  {
    id: 100,
    parentId: null,
    title: '商品库',
    icon: 'CodepenOutlined',
    component: 'RouteView',
    redirect: '/commodity/list',
    path: '/commodity',
    name: 'Commodity',
    locale: '商品库',
  },
  {
    id: 101,
    parentId: 100,
    title: '商品列表',
    component: '/commodity/table',
    path: '/commodity/list',
    name: 'CommodityIndex',
    locale: '商品列表',
  },
  {
    id: 102,
    parentId: 100,
    title: '商品新增',
    component: '/commodity/form',
    path: '/commodity/form',
    name: 'CommodityForm',
    locale: '商品新增',
  },
  {
    id: 200,
    parentId: null,
    title: '仓库管理',
    icon: 'DatabaseOutlined',
    component: 'RouteView',
    path: '/storage',
    name: 'Storage',
    locale: '仓库管理',
  },
  {
    id: 201,
    parentId: 200,
    title: '已授权仓库列表',
    component: '/storage/vendor/list',
    path: '/storage/vendor/list',
    name: 'StorageVendorList',
    locale: '已授权仓库列表',
  },
  {
    id: 202,
    parentId: 200,
    title: '仓库授权',
    component: '/storage/vendor/auth',
    path: '/storage/vendor/auth',
    name: 'StorageVendorAuth',
    locale: '仓库授权',
  }
]

export const salerAccessMenuData = [
  {
    id: 100,
    parentId: null,
    title: '商品库',
    icon: 'CodepenOutlined',
    component: 'RouteView',
    redirect: '/commodity/list',
    path: '/commodity',
    name: 'Commodity',
    locale: '商品库',
  },
  {
    id: 101,
    parentId: 100,
    title: '商品列表',
    component: '/commodity/table',
    path: '/commodity/list',
    name: 'CommodityIndex',
    locale: '商品列表',
  },
  {
    id: 102,
    parentId: 100,
    title: '商品新增',
    component: '/commodity/form',
    path: '/commodity/form',
    name: 'CommodityForm',
    locale: '商品新增',
  },
  {
    id: 303,
    parentId: 300,
    title: '退换货',
    component: '/order/RAE',
    path: '/order/RAE',
    name: 'OrderRAE',
    locale: '退换货',
  },
  {
    id: 500,
    parentId: null,
    title: '数据分析与统计',
    icon: 'CodepenOutlined',
    component: 'RouteView',
    redirect: '/statistics/BusinessOverview',
    path: '/statistics',
    name: 'Statistics',
    locale: '数据分析与统计',
  },
  {
    id: 501,
    parentId: 500,
    title: '经营总览',
    component: '/statistics/saler/BusinessOverview',
    path: '/statistics/saler/BusinessOverview',
    name: 'StatisticsSalerBusinessOverview',
    locale: '经营总览',
  },
  {
    id: 502,
    parentId: 500,
    title: '商品分析',
    component: '/statistics/saler/CommodityAnalyze',
    path: '/statistics/saler/CommodityAnalyze',
    name: 'StatisticsSalerCommodityAnalyze',
    locale: '商品分析',
  }
]

export const storageAccessMenuData = [
  {
    id: 600,
    parentId: null,
    title: '仓库管理',
    icon: 'CodepenOutlined',
    component: 'RouteView',
    redirect: '/storage_manager/list',
    path: '/storage_manager',
    name: 'StorageManager',
    locale: '仓库管理',
  },
  {
    id: 601,
    parentId: 600,
    title: '仓库管理',
    component: '/storage/storage_manager/list',
    path: '/storage_manager/list',
    name: 'StorageManagerList',
    locale: '仓库管理',
  },
  {
    id: 602,
    parentId: 600,
    title: '出入库管理',
    component: '/storage/storage_manager/io',
    path: '/storage_manager/io',
    name: 'StorageManagerIO',
    locale: '出入库管理',
  },
  {
    id: 603,
    parentId: 600,
    title: '品牌授权',
    component: '/storage/storage_manager/brand_auth',
    path: '/storage_manager/brand_auth',
    name: 'StorageManagerBrandAuth',
    locale: '品牌授权',
  },
  {
    id: 604,
    parentId: 600,
    title: '库存管理',
    component: '/storage/storage_manager/storage',
    path: '/storage_manager/storage',
    name: 'StorageManagerBrandStorage',
    locale: '库存管理',
  }
]

export const accessMenuData = [
  {
    id: 18,
    parentId: 15,
    path: '/access/admin',
    title: '管理员',
    name: 'AccessAdmin',
    component: '/access/admin',
    locale: 'menu.access.admin',
  }
]

export const RouteMap = new Map<String, Array<Object>>([
  ['VENDOR', vendorAccessMenuData],
  ['SALER', salerAccessMenuData],
  ['STORAGE_MANAGER', storageAccessMenuData],
  ['ADMIN', vendorAccessMenuData]
])

export function getRouteMenusApi() {
  const role = window.localStorage.getItem('role')
  return {
    code: 200,
    msg: '获取成功',
    data: [...menuData.slice(0, menuData.length-3), ...RouteMap.get(ROLES_ARRAY[role]), ...menuData.slice(menuData.length-3)],
  }
}
