const menuData = [
  {
    id: 1,
    parentId: null,
    title: '仪表盘',
    icon: 'DashboardOutlined',
    component: 'RouteView',
    redirect: '/dashboard/analysis',
    path: '/dashboard',
    name: 'Dashboard',
    locale: 'menu.dashboard',
  },
  {
    id: 2,
    parentId: 1,
    title: '分析页',
    component: '/dashboard/analysis',
    path: '/dashboard/analysis',
    name: 'DashboardAnalysis',
    keepAlive: true,
    locale: 'menu.dashboard.analysis',
  },
  {
    id: 15,
    path: '/access',
    component: 'RouteView',
    redirect: '/access/common',
    title: '权限模块',
    name: 'Access',
    parentId: null,
    icon: 'ClusterOutlined',
    locale: 'menu.access',
  },
  {
    id: 16,
    parentId: 15,
    path: '/access/common',
    title: '通用权限',
    name: 'AccessCommon',
    component: '/access/common',
    locale: 'menu.access.common',
  },
  {
    id: 17,
    parentId: 15,
    path: '/access/user',
    title: '普通用户',
    name: 'AccessUser',
    component: '/access/user',
    locale: 'menu.access.user',
  },
  {
    id: 300,
    parentId: null,
    title: '订单管理',
    icon: 'CreditCardOutlined',
    component: 'RouteView',
    path: '/order',
    name: 'Order',
    locale: '订单管理',
  },
  {
    id: 301,
    parentId: 300,
    title: '订单列表',
    component: '/order/vendor/list',
    path: '/order/vendor/list',
    name: 'OrderVendorList',
    locale: '订单列表',
  },
  {
    id: 302,
    parentId: 300,
    title: '添加订单',
    component: '/order/vendor/form',
    path: '/order/vendor/form',
    name: 'OrderVendorForm',
    locale: '添加订单',
  },
  {
    id: 400,
    parentId: null,
    title: '财务管理',
    icon: 'PayCircleOutlined',
    component: 'RouteView',
    path: '/finance',
    name: 'Finance',
    locale: '财务管理',
  },
  {
    id: 401,
    parentId: 400,
    title: '财务流水',
    component: '/finance/vendor/waterfall',
    path: '/finance/vendor/waterfall',
    name: 'FinanceVendorWaterfall',
    locale: '财务流水',
  },
  {
    id: 402,
    parentId: 400,
    title: '财务统计',
    component: '/finance/vendor/statistics',
    path: '/finance/vendor/statistics',
    name: 'FinanceVendorStatistics',
    locale: '财务统计',
  },
  {
    id: 36,
    parentId: null,
    title: '个人页',
    icon: 'UserOutlined',
    component: 'RouteView',
    redirect: '/account/center',
    path: '/account',
    name: 'Account',
    locale: 'menu.account',
  },
  {
    id: 37,
    parentId: 36,
    path: '/account/center',
    title: '个人中心',
    name: 'AccountCenter',
    component: '/account/center',
    locale: 'menu.account.center',
  },
  {
    id: 38,
    parentId: 36,
    path: '/account/settings',
    title: '个人设置',
    name: 'AccountSettings',
    component: '/account/settings',
    locale: 'menu.account.settings',
  }
]

export const vendorAccessMenuData = [
  {
    id: 100,
    parentId: null,
    title: '商品库',
    icon: 'CodepenOutlined',
    component: 'RouteView',
    redirect: '/commodity/list',
    path: '/commodity',
    name: 'Commodity',
    locale: '商品库',
  },
  {
    id: 101,
    parentId: 100,
    title: '商品列表',
    component: '/commodity/table',
    path: '/commodity/list',
    name: 'CommodityIndex',
    locale: '商品列表',
  },
  {
    id: 102,
    parentId: 100,
    title: '商品新增',
    component: '/commodity/form',
    path: '/commodity/form',
    name: 'CommodityForm',
    locale: '商品新增',
  },
  {
    id: 200,
    parentId: null,
    title: '仓库管理',
    icon: 'DatabaseOutlined',
    component: 'RouteView',
    path: '/storage',
    name: 'Storage',
    locale: '仓库管理',
  },
  {
    id: 201,
    parentId: 200,
    title: '已授权仓库列表',
    component: '/storage/vendor/list',
    path: '/storage/vendor/list',
    name: 'StorageVendorList',
    locale: '已授权仓库列表',
  },
  {
    id: 202,
    parentId: 200,
    title: '仓库授权',
    component: '/storage/vendor/auth',
    path: '/storage/vendor/auth',
    name: 'StorageVendorAuth',
    locale: '仓库授权',
  }
]

export const accessMenuData = [
  {
    id: 18,
    parentId: 15,
    path: '/access/admin',
    title: '管理员',
    name: 'AccessAdmin',
    component: '/access/admin',
    locale: 'menu.access.admin',
  }
]

const RouteMap = new Map<String, Object[]>([
  ['VENDOR', vendorAccessMenuData],
  ['SALER', vendorAccessMenuData],
  ['STORAGE_MANAGER', vendorAccessMenuData],
  ['ADMIN', vendorAccessMenuData]
])

export default eventHandler((event: any) => {
  const token = getHeader(event, 'Authorization')
  const username = Buffer.from(token, 'base64').toString('utf-8')
  return {
    code: 200,
    msg: '获取成功',
    data: [...menuData.slice(0, menuData.length-3), ...(username === 'admin' ? vendorAccessMenuData : []), ...menuData.slice(menuData.length-3)],
  }
})
